// <auto-generated />
using System;
using Enforcement.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enforcement.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EnforcementDbContext))]
    [Migration("20260920051502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enforcement.Api.Domain.ActionTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EnforcementDomainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutcomeKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementDomainId", "Code")
                        .IsUnique();

                    b.ToTable("action_types", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementCaseId");

                    b.ToTable("case_audit_events", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementCaseId")
                        .IsUnique();

                    b.ToTable("case_subjects", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OffenceNumberApplied")
                        .HasColumnType("integer");

                    b.Property<Guid>("ViolationTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementCaseId");

                    b.HasIndex("ViolationTypeId");

                    b.ToTable("case_violations", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FinancialObligationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedByKeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("EnforcementCaseId");

                    b.ToTable("enforcement_actions", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedOfficerKeycloakUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByKeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EnforcementDomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationLabel")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("EnforcementDomainId");

                    b.ToTable("enforcement_cases", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("enforcement_domains", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CapturedByKeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UriOrValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementCaseId");

                    b.ToTable("evidence_items", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.FinancialObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnforcementActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnforcementCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalPaymentReference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementCaseId");

                    b.ToTable("financial_obligations", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.PenaltyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OffenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ViolationTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViolationTypeId");

                    b.ToTable("penalty_rules", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.SubjectTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EnforcementDomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSystemHint")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementDomainId", "Code")
                        .IsUnique();

                    b.ToTable("subject_types", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.ViolationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EnforcementDomainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnforcementDomainId", "Code")
                        .IsUnique();

                    b.ToTable("violation_types", (string)null);
                });

            modelBuilder.Entity("Enforcement.Api.Domain.ActionTypeDefinition", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementDomain", "EnforcementDomain")
                        .WithMany("ActionTypes")
                        .HasForeignKey("EnforcementDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementDomain");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseAuditEvent", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithMany("AuditEvents")
                        .HasForeignKey("EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementCase");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseSubject", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithOne("Subject")
                        .HasForeignKey("Enforcement.Api.Domain.CaseSubject", "EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementCase");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.CaseViolation", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithMany("Violations")
                        .HasForeignKey("EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enforcement.Api.Domain.ViolationType", "ViolationType")
                        .WithMany()
                        .HasForeignKey("ViolationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementCase");

                    b.Navigation("ViolationType");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementAction", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.ActionTypeDefinition", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithMany("Actions")
                        .HasForeignKey("EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("EnforcementCase");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementCase", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementDomain", "EnforcementDomain")
                        .WithMany()
                        .HasForeignKey("EnforcementDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementDomain");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EvidenceItem", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithMany("Evidence")
                        .HasForeignKey("EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementCase");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.FinancialObligation", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementCase", "EnforcementCase")
                        .WithMany("FinancialObligations")
                        .HasForeignKey("EnforcementCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementCase");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.PenaltyRule", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.ViolationType", "ViolationType")
                        .WithMany("PenaltyRules")
                        .HasForeignKey("ViolationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViolationType");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.SubjectTypeDefinition", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementDomain", "EnforcementDomain")
                        .WithMany("SubjectTypes")
                        .HasForeignKey("EnforcementDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementDomain");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.ViolationType", b =>
                {
                    b.HasOne("Enforcement.Api.Domain.EnforcementDomain", "EnforcementDomain")
                        .WithMany("ViolationTypes")
                        .HasForeignKey("EnforcementDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnforcementDomain");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementCase", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("AuditEvents");

                    b.Navigation("Evidence");

                    b.Navigation("FinancialObligations");

                    b.Navigation("Subject");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.EnforcementDomain", b =>
                {
                    b.Navigation("ActionTypes");

                    b.Navigation("SubjectTypes");

                    b.Navigation("ViolationTypes");
                });

            modelBuilder.Entity("Enforcement.Api.Domain.ViolationType", b =>
                {
                    b.Navigation("PenaltyRules");
                });
#pragma warning restore 612, 618
        }
    }
}
